### ISSUE TITLE
Handle NUnit's Assert.Fail

### ISSUE THREAD

**Issue by waf** [Jetabroad/NunitToXunit#9]
As per https://stackoverflow.com/a/51945814

We can convert NUnit's `Assert.Fail("message")` to either `Assert.True(false, "message")`, or maybe `throw new Xunit.Sdk.XunitException(message)`

**Comment by aixasz** [comment]
I'm going to close this issue. It seems you already handled this. 

https://github.com/Jetabroad/NunitToXunit/blob/master/src/NUnitToXUnit/Features/ConvertAsserts/ConvertThatExpression.cs#L30
